### ISSUE TITLE
Unclear error on missed `this[NAMESPACE].options.manifest`

### ISSUE THREAD

**Issue by ai** [usmanyunusov/webpack-webmanifest-plugin#4]
I added plugin to webpack. For some reason, `loader` doesn’t work.

But the error is unclear. It will be better to explain that `loader` didn’t load the manifest and suggested solution.

```
(node:63462) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at /home/ai/Dev/akeero-front/node_modules/webpack-webmanifest-plugin/src/index.js:50:67
    at Hook.eval [as call] (eval at create (/home/ai/Dev/akeero-front/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/home/ai/Dev/akeero-front/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at /home/ai/Dev/akeero-front/node_modules/webpack/lib/Compilation.js:2513:40
    at eval (eval at create (/home/ai/Dev/akeero-front/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

I use webpack 5.

**Comment by usmanyunusov** [comment]
Thank! Fixed :)
