### ISSUE TITLE
Loader doesn’t work

### ISSUE THREAD

**Issue by ai** [usmanyunusov/webpack-webmanifest-plugin#5]
Loader in webpack config:

```js
      {
        test: /\.webmanifest$/,
        use: [{ loader: WebManifestPlugin.loader }]
      },
```

Plugins:

```js
[
  new WebManifestPlugin(),
  new HtmlWebpackPlugin({ template: './view/index.html' }),
  new DefinePlugin({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
  })
]
```

HTML template:

```html
    <link rel="manifest" href="<%=
      require('../layout/base/manifest.webmanifest')
    %>" />
```

Manifest:

```json
{
  "start_url": ".",
  "background_color": "#363636",
  "theme_color": "#363636",
  "icons": []
}
```

Result:

```
NODE_ENV=production npx webpack
(node:67435) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at /home/ai/Dev/akeero-front/node_modules/webpack-webmanifest-plugin/src/index.js:50:67
    at Hook.eval [as call] (eval at create (/home/ai/Dev/akeero-front/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/home/ai/Dev/akeero-front/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at /home/ai/Dev/akeero-front/node_modules/webpack/lib/Compilation.js:2513:40
    at eval (eval at create (/home/ai/Dev/akeero-front/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by usmanyunusov** [comment]
Fixed! 

Need to add support assets loader

```js
{
      test: /\.(png|jpg|jpeg|svg|webp)$/,
      type: 'asset/resource',
},
```
